# --> check the Python program
# - DIR/DIR/main.py:
#  - description: Ensure that the main.py file exists in the SRC directory
#    check: ConfirmFileExists
#  - description: Complete all TODOs, remove the TODO markers in the main.py
#    check: MatchFileFragment
#    options:
#      fragment: TODO
#      count: 0
#      exact: true
  # - description: Create a sufficient number of docstring (i.e., multiple-line) comments in main.py
  #   check: CountMultipleLineComments
  #   options:
  #     language: "Python"
  #     count: 3
  #     exact: false
  # - description: Create a sufficient number of single-line comments in main.py
  #   check: CountSingleLineComments
  #   options:
  #     language: "Python"
  #     count: 6
  #     exact: false

# --> check the technical writing for various characteristics
- writing/reflection.md:
  - description: Ensure that reflection.md file exists in the writing/ directory
    check: ConfirmFileExists
  - description: Write a minimum number of meaningful words (adding around 100 words in total) in the reflection
    check: CountFileWords
    options:
      count: 550
      exact: false
  # - description: Confirm that the markdown file has the correct number of headers
  #   check: CountMarkdownTags
  #   options:
  #     tag: heading
  #     count: 9
  #     exact: true
  # - description: Confirm that the markdown file has the correct number of code blocks
  #   check: CountMarkdownTags
  #   options:
  #     tag: code_block
  #     count: 4
  #     exact: true
  - description: Complete all TODOs, remove the TODO markers in the reflection.md
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the reflection file
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true

# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (5) in repository
  check: CountCommits
  options:
    count: 5

